### ISSUE TITLE
[BE] ERD 설계

### ISSUE THREAD

**Issue by kyungrae** [codesquad-member-2020/todo-7#2]
Todo 관리 애플리케이션 구현을 위해 필요한 최소 테이블 구조 설계

**Comment by kyungrae** [comment]
# ERD ver. 0.0.1

요구사항을 만족하기 위해 필요한 필수 테이블 설계를 했다. issue 객체가 순서를 갖게하도록 하기위해 **order column**, **next reference** 두가지 방법에 대해서 고민했다. 리스트에 insert, delete 연산이 많이 진행되기 때문에 order 방식보다 refrence 방식을 사용하기로 결정했다.

History에 필요한 외래키는 Category entiry와 Card entity 기능이 완성된 후 추가한다. User 테이블과 Board 테이블은 기능이 추가될 때 설계하기로 한다.

![ERD](https://user-images.githubusercontent.com/26711771/78751776-cfc02280-79ad-11ea-9544-1b4fa3dcfd74.png)

> reference
https://blog.theodorejb.me/sql-linked-lists/
https://dba.stackexchange.com/questions/46238/linked-list-in-sql-and-trees
https://stackoverflow.com/questions/65205/linked-list-in-sql

**Comment by suhyunsim** [comment]
![Screenshot from 2020-04-08 17-18-43](https://user-images.githubusercontent.com/58318786/78761072-0ea9a480-79bd-11ea-983f-1d320b1793f9.png)

**Comment by kyungrae** [comment]
# ERD ver. 0.0.2

전체를 식별할 수 있는 project를 root entity로 지정했다. 또한 spring data jdbc 모듈에서 1:N 관계의 순서를 나타내기 위해 key column을 사용한다. 순서를 유지하기 위해 외래키를 사용하지 않고 spring data jdbc에서 제공하는 기능을 사용할 예정이다.

![erd2](https://user-images.githubusercontent.com/26711771/78857422-52a3b480-7a64-11ea-97ee-12e7b0a1c5b2.png)

> reference
https://docs.spring.io/spring-data/jdbc/docs/1.1.6.RELEASE/reference/html/#jdbc.entity-persistence
https://docs.spring.io/spring-data/jdbc/docs/1.1.6.RELEASE/reference/html/#jdbc.entity-persistence.types
