### ISSUE TITLE
프로젝트활동 리뷰

### ISSUE THREAD

**Issue by crongro** [codesquad-member-2020/todo-7#20]
잘 활동하시고 계세요.

오  기능요구사항 정리 굿.  issue-id 만드는 거 좋죠. 커뮤니케이션할때도 번호로 말하면 서로 알고요. 이 문서를 2주동안  계속 업데이트하면 좋겠어요. 아주 재미 없는 일이지만 개발할때 개발자가 신경써야 하는 일이긴해요.

조장도 있군에. 책임을 서로 같이  갖는거 좋아보여요.

PR을 보낼때 issue번호 연결하는 거 아주 좋습니다. 
https://github.com/codesquad-member-2020/todo-7/pull/18
실무에서도 이렇게 하면서 PR에 대해서 관련이슈를 점검하기도 합니다.

PR이 아직 많지  않은데, feature 를 너무 큰 단위로(오래 걸리는 일로)만들지 않고 작게 만들고 자주 DEV에 합치면 좋겠어요. 일을 작게 나누는 것도 어려운일이긴해요. 우리는 그런 훈련이 필요합니다 ^^

**Comment by GangWoon** [comment]
네~~
